spring:
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    hikari:
      connection-timeout: 30000   # 30 seconds - reasonable wait time
      maximum-pool-size: 150      # Bounded pool - well below MySQL max_connections
      minimum-idle: 20            # Reasonable minimum
      idle-timeout: 600000        # 10 minutes
      pool-name: VT-Pool
      max-lifetime: 1800000       # 30 minutes
      auto-commit: true
      connection-test-query: "SELECT 1"
      validation-timeout: 5000    # 5 seconds
      leak-detection-threshold: 15000  # 15 seconds - detect leaks early
      register-mbeans: true
      allow-pool-suspension: false
    url: jdbc:mysql://localhost:3309/product_management?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    testWhileIdle: true
    username: yu71
    password: 53cret
    validationQuery: SELECT 1
  flyway:
    baseline-version: 0
    enabled: true
    validate-on-migrate: false
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: none
    open-in-view: false  # Disable OSIV to prevent connection leaks
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: false



